databaseconnection/Controllers/yerraController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using MySql.Data.MySqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using jindal.Models;

namespace jindal.Controllers
{
    public class yerraController : Controller
    {
        // Reference for connec 
        //server = "pc-name-whateveritis";
        //database = "restaurantdb";
        //uid = "root";
        //password = "";
        //string connectionString;
        //connectionString = "SERVER=" + server + "; PORT = 3306 ;" + "DATABASE=" + database + ";" + "UID=" + uid + ";" + "PASSWORD=" + password + ";";

        //string s = @"Provider=MySql.Data.MySqlClient;server = 166.62.10.49; user id = reassure93;database=ReassureRFIDDb;password:Reassure@@2016";
        string s = "Data Source = 166.62.10.49; port=3306;Initial Catalog = ReassureRFIDDb; User Id = reassure93; password=Reassure@2016";
        //"data source=166.62.10.49;initial catalog=ReassureRFIDDb;integrated security=True;";
        // GET: yerra
        public ActionResult Index()

        {
           
            List<fordb> qwe = new List<fordb>();
           
            return View();
        }

        [HttpPost]
        public ActionResult Insert(string userid,string pass_word)
        {
            MySqlConnection asd = new MySqlConnection();
            asd.ConnectionString = s;
            asd.Open();
            MySqlCommand asd1 = new MySqlCommand();
            asd1.Connection = asd;
            asd1.CommandText = String.Format("insert into ReassureRFIDDb.sky(userid,pass_word) values({0},'{1}');",userid,pass_word);
            int i = asd1.ExecuteNonQuery();
            if (i > 0)
            {
                ViewBag.msg = "Successfully Inserted";
            }
            else
            {
                ViewBag.msg = "Not Inserted";
            }
            asd.Close();
            return View("Index");
        }


        public ActionResult Delete(string userid)
        {
            MySqlConnection asd = new MySqlConnection();
            asd.ConnectionString = s;
            asd.Open();
            MySqlCommand asd1 = new MySqlCommand();
            asd1.Connection = asd;
            asd1.CommandText = String.Format("delete  from  sai where userid ={0})", userid);
            int i = asd1.ExecuteNonQuery();
            if (i > 0)
            {
                ViewBag.msg = "Successfully Deleted";
            }
            else
            {
                ViewBag.msg = "Not Deleted";
            }
            asd.Close();
            return View("Index");
        }
    }
}

databaseconnection/Views/yerra/Index.cshtml
@model jindal.Models.fordb

@{
    Layout = null;
}

<!DOCTYPE html>+/

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h1>@ViewBag.msg</h1>

    @using (Html.BeginForm("Insert","yerra",FormMethod.Post)) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>fordb</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.userid, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                   
                    @Html.EditorFor(model => model.userid, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.userid, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.pass_word, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.pass_word, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.pass_word, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>+
        </div>
    }
    
    <div>

    </div>
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>